language: php

php:
  - 7.2
  - 7.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install --no-interaction

script:
  - ./vendor/bin/parallel-lint . --exclude vendor
  - composer test -- --coverage-clover=build/coverage.xml

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
