language: php

php:
  - 7.2
  - 7.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install --no-interaction

script:
  - ./vendor/bin/parallel-lint . --exclude vendor
  - mkdir -p build/logs 
  - composer test -- --coverage-clover=build/logs/coverage.xml

after_success:
- travis_retry php vendor/bin/php-coveralls

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
